version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
  target-branch: development
  ignore:
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.12.13
    - 7.12.16
    - 7.12.17
    - 7.13.10
    - 7.13.15
    - 7.13.8
    - 7.13.9
  - dependency-name: eslint-plugin-react
    versions:
    - 7.23.2
  - dependency-name: webpack
    versions:
    - 5.17.0
    - 5.19.0
    - 5.21.2
    - 5.23.0
    - 5.24.2
    - 5.24.3
    - 5.25.1
    - 5.27.1
    - 5.30.0
    - 5.31.2
  - dependency-name: mini-css-extract-plugin
    versions:
    - 1.3.4
    - 1.3.5
    - 1.3.6
    - 1.3.8
    - 1.3.9
    - 1.4.1
  - dependency-name: "@babel/core"
    versions:
    - 7.13.14
  - dependency-name: classnames
    versions:
    - 2.3.1
  - dependency-name: sass-loader
    versions:
    - 10.1.1
    - 11.0.0
    - 11.0.1
  - dependency-name: eslint
    versions:
    - 7.18.0
    - 7.19.0
    - 7.20.0
    - 7.21.0
    - 7.22.0
  - dependency-name: semantic-release
    versions:
    - 17.3.7
    - 17.3.9
    - 17.4.0
    - 17.4.1
    - 17.4.2
  - dependency-name: postcss-loader
    versions:
    - 4.2.0
    - 5.0.0
    - 5.1.0
  - dependency-name: webpack-cli
    versions:
    - 4.4.0
    - 4.5.0
  - dependency-name: replace-in-file
    versions:
    - 6.2.0
  - dependency-name: ini
    versions:
    - 1.3.8
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
  target-branch: development
  ignore:
  - dependency-name: squizlabs/php_codesniffer
    versions:
    - 3.6.0
  - dependency-name: codeinwp/themeisle-sdk
    versions:
    - 3.2.18
    - 3.2.19
    - 3.2.20
  - dependency-name: codeinwp/gutenberg-css
    versions:
    - 1.1.1
