---
branch: master
plugins:
  - - "@semantic-release/commit-analyzer"
    - preset: simple-preset
      releaseRules: conventional-changelog-simple-preset/release-rules
  - - "@semantic-release/changelog"
    - changelogFile: CHANGELOG.md
  - - "@semantic-release/release-notes-generator"
    - preset: simple-preset
  - - "@semantic-release/exec"
    - prepareCmd: 'export nextReleaseNotes="${nextRelease.notes}" && node bin/update-changelog.mjs'
  - - "@semantic-release/exec"
    - prepareCmd: grunt version::${nextRelease.version} && grunt wp_readme_to_markdown
  - - "semantic-release-slack-bot"
    - notifyOnSuccess: false
      notifyOnFail: false
      markdownReleaseNotes: true
      branchesConfig:
        - pattern: master
          notifyOnSuccess: true
          notifyOnFail: false
  - - "@semantic-release/git"
    - assets:
        - CHANGELOG.md
        - composer.json
        - composer.lock
        - package-lock.json
        - package-lock.json
        - readme.txt
        - otter-blocks.php
        - readme.md
        - package.json
        - plugins/otter-pro/otter-pro.php
        - plugins/blocks-animation/blocks-animation.php
        - plugins/blocks-animation/readme.md
        - plugins/blocks-animation/readme.txt
        - plugins/blocks-css/blocks-css.php
        - plugins/blocks-css/readme.md
        - plugins/blocks-css/readme.txt
        - plugins/blocks-export-import/blocks-export-import.php
        - plugins/blocks-export-import/readme.md
        - plugins/blocks-export-import/readme.txt
      message: "chore(release): ${nextRelease.version} \n\n${nextRelease.notes}"
  - - "@semantic-release/github"
