<?php
/**
 * Call to Action
 *
 * @package ThemeIsle
 */

return array(
	'title'      => __( 'Call to Action', 'otter-blocks' ),
	'categories' => array( 'otter-blocks', 'cta' ),
	'content'    => '<!-- wp:themeisle-blocks/advanced-columns {"id":"wp-block-themeisle-blocks-advanced-columns-678cc482","columns":1,"layout":"equal","layoutMobile":"collapsedRows","padding":{"top":"64px","right":"24px","bottom":"64px","left":"24px"},"paddingTablet":{"top":"64px","right":"24px","bottom":"64px","left":"24px"},"paddingMobile":{"top":"40px","bottom":"40px"},"margin":{"top":"0px","bottom":"0px"},"columnsWidth":960,"horizontalAlign":"center","columnsHeightCustom":600,"verticalAlign":"bottom","backgroundType":"image","backgroundImage":{"id":261,"url":"https://demosites.io/otter/wp-content/uploads/sites/664/2022/09/image-from-rawpixel-id-1054551-jpeg.jpg"},"backgroundAttachment":"fixed","backgroundPosition":{"x":"0.50","y":"0.56"},"backgroundRepeat":"no-repeat","backgroundSize":"cover","backgroundOverlayOpacity":30,"backgroundOverlayColor":"#000000","reverseColumnsMobile":true,"align":"full","className":"ticss-c00aadba","hasCustomCSS":true,"customCSS":""} --><div id="wp-block-themeisle-blocks-advanced-columns-678cc482" class="wp-block-themeisle-blocks-advanced-columns alignfull has-1-columns has-desktop-equal-layout has-tablet-equal-layout has-mobile-collapsedRows-layout has-reverse-columns-mobile has-vertical-bottom ticss-c00aadba"><div class="wp-block-themeisle-blocks-advanced-columns-overlay"></div><div class="innerblocks-wrap"><!-- wp:themeisle-blocks/advanced-column {"id":"wp-block-themeisle-blocks-advanced-column-4d412c51","padding":{"top":"0px","right":"0px","bottom":"0px","left":"0px"},"paddingMobile":{"top":"0px","right":"0px","bottom":"0px","left":"0px"},"columnWidth":"100"} --><div id="wp-block-themeisle-blocks-advanced-column-4d412c51" class="wp-block-themeisle-blocks-advanced-column"><!-- wp:themeisle-blocks/advanced-heading {"id":"wp-block-themeisle-blocks-advanced-heading-fb3c7a39","align":"center","alignTablet":"center","alignMobile":"center","headingColor":"#ffffff","fontSize":56,"fontSizeTablet":40,"fontSizeMobile":32} --><h2 id="wp-block-themeisle-blocks-advanced-heading-fb3c7a39" class="wp-block-themeisle-blocks-advanced-heading wp-block-themeisle-blocks-advanced-heading-fb3c7a39">A call to action section</h2><!-- /wp:themeisle-blocks/advanced-heading --><!-- wp:paragraph {"align":"center","style":{"color":{"text":"#fefefe"}}} --><p class="has-text-align-center has-text-color" style="color:#fefefe">A Call to action section</p><!-- /wp:paragraph --><!-- wp:buttons {"layout":{"type":"flex","justifyContent":"center"}} --><div class="wp-block-buttons"><!-- wp:button {"className":"is-style-primary"} --><div class="wp-block-button is-style-primary"><a class="wp-block-button__link">Learn More</a></div><!-- /wp:button --></div><!-- /wp:buttons --></div><!-- /wp:themeisle-blocks/advanced-column --></div></div><!-- /wp:themeisle-blocks/advanced-columns -->', // phpcs:ignore WordPressVIPMinimum.Security.Mustache.OutputNotation
);
