<?php
/**
 * Large Quote
 *
 * @package ThemeIsle
 */

return array(
	'title'      => __( 'Large Quote', 'otter-blocks' ),
	'categories' => array( 'otter-blocks', 'text' ),
	'content'    => '<!-- wp:themeisle-blocks/advanced-columns {"id":"wp-block-themeisle-blocks-advanced-columns-02d86e0d","columns":1,"layout":"equal","layoutMobile":"collapsedRows","padding":{"top":"64px","right":"24px","bottom":"64px","left":"24px"},"paddingTablet":{"top":"64px","right":"24px","bottom":"64px","left":"24px"},"paddingMobile":{"top":"40px","bottom":"40px"},"margin":{"top":"0px","bottom":"0px"},"columnsWidth":1140,"horizontalAlign":"center","verticalAlign":"center","align":"full","className":"ticss-c00aadba","hasCustomCSS":true,"customCSS":""} --><div id="wp-block-themeisle-blocks-advanced-columns-02d86e0d" class="wp-block-themeisle-blocks-advanced-columns alignfull has-1-columns has-desktop-equal-layout has-tablet-equal-layout has-mobile-collapsedRows-layout has-vertical-center ticss-c00aadba"><div class="wp-block-themeisle-blocks-advanced-columns-overlay"></div><div class="innerblocks-wrap"><!-- wp:themeisle-blocks/advanced-column {"id":"wp-block-themeisle-blocks-advanced-column-853c0cd5","padding":{"top":"0px","right":"0px","bottom":"0px","left":"0px"},"paddingMobile":{"top":"0px","right":"0px","bottom":"0px","left":"0px"},"margin":{"top":"0px","right":"12px","bottom":"0px","left":"12px"},"marginMobile":{"right":"0px","bottom":"24px","left":"0px"},"columnWidth":"100"} --><div id="wp-block-themeisle-blocks-advanced-column-853c0cd5" class="wp-block-themeisle-blocks-advanced-column"><!-- wp:themeisle-blocks/advanced-heading {"id":"wp-block-themeisle-blocks-advanced-heading-15dd99e6","tag":"p","align":"center","alignTablet":"center","alignMobile":"center","fontSize":56,"fontSizeTablet":40,"fontSizeMobile":32,"fontStyle":"italic"} --><p id="wp-block-themeisle-blocks-advanced-heading-15dd99e6" class="wp-block-themeisle-blocks-advanced-heading wp-block-themeisle-blocks-advanced-heading-15dd99e6">"...The greatest victory is that which requires no battle...."</p><!-- /wp:themeisle-blocks/advanced-heading --><!-- wp:themeisle-blocks/advanced-heading {"id":"wp-block-themeisle-blocks-advanced-heading-0d3c3162","tag":"p","align":"center","alignTablet":"center","alignMobile":"center","fontSize":12,"fontSizeTablet":12,"fontSizeMobile":12,"textTransform":"uppercase"} --><p id="wp-block-themeisle-blocks-advanced-heading-0d3c3162" class="wp-block-themeisle-blocks-advanced-heading wp-block-themeisle-blocks-advanced-heading-0d3c3162"><strong>Sun Tzu, The Art of War</strong></p><!-- /wp:themeisle-blocks/advanced-heading --></div><!-- /wp:themeisle-blocks/advanced-column --></div></div><!-- /wp:themeisle-blocks/advanced-columns -->',
);
