<?php
/**
 * Text Lead Statement (Atomic Wind)
 *
 * @package ThemeIsle
 */

return array(
	'title'       => __( 'Text Lead Statement', 'otter-blocks' ),
	'categories'  => array( 'otter-blocks', 'text' ),
	'description' => __( 'Dark centered mission statement section with a large lead paragraph and author byline, ideal for company values, brand manifesto, or about-us intro copy', 'otter-blocks' ),
	'content'     => '<!-- wp:atomic-wind/box {"tagName":"section","align":"full","className":"bg-neutral-950 px-6 py-28"} --><section class="wp-block-atomic-wind-box alignfull bg-neutral-950 px-6 py-28"><!-- wp:atomic-wind/box {"className":"mx-auto flex max-w-3xl flex-col items-center gap-8 text-center"} --><div class="wp-block-atomic-wind-box mx-auto flex max-w-3xl flex-col items-center gap-8 text-center"><!-- wp:atomic-wind/box {"className":"inline-flex items-center gap-2 self-start rounded-full border border-white/15 bg-white/5 px-4 py-1.5"} --><div class="wp-block-atomic-wind-box inline-flex items-center gap-2 self-start rounded-full border border-white/15 bg-white/5 px-4 py-1.5"><!-- wp:atomic-wind/icon {"icon":"flag","className":"size-4 text-indigo-300 m-0"} /--><!-- wp:atomic-wind/text {"tagName":"span","className":"text-sm font-semibold text-indigo-200 m-0"} --><span class="wp-block-atomic-wind-text text-sm font-semibold text-indigo-200 m-0" data-rich-text="">Our mission</span><!-- /wp:atomic-wind/text --></div><!-- /wp:atomic-wind/box --><!-- wp:atomic-wind/text {"tagName":"p","className":"text-3xl font-semibold leading-snug text-white md:text-4xl m-0"} --><p class="wp-block-atomic-wind-text text-3xl font-semibold leading-snug text-white md:text-4xl m-0" data-rich-text="">We are here to give every team the tools to ship their best work &#8212; without the busywork, the bloat, or the endless tabs. <span class="text-indigo-400">Simplicity is the whole product.</span></p><!-- /wp:atomic-wind/text --><!-- wp:atomic-wind/box {"className":"flex items-center gap-4"} --><div class="wp-block-atomic-wind-box flex items-center gap-4"><!-- wp:atomic-wind/image {"url":"https://picsum.photos/seed/tlead-q/96/96","alt":"Author","className":"size-12 rounded-full object-cover m-0"} --><img class="wp-block-atomic-wind-image size-12 rounded-full object-cover m-0" src="https://picsum.photos/seed/tlead-q/96/96" alt="Author"/><!-- /wp:atomic-wind/image --><!-- wp:atomic-wind/box {"className":"flex flex-col items-start"} --><div class="wp-block-atomic-wind-box flex flex-col items-start"><!-- wp:atomic-wind/text {"tagName":"span","className":"text-base font-bold text-white m-0"} --><span class="wp-block-atomic-wind-text text-base font-bold text-white m-0" data-rich-text="">Maya Okonkwo</span><!-- /wp:atomic-wind/text --><!-- wp:atomic-wind/text {"tagName":"span","className":"text-sm text-neutral-400 m-0"} --><span class="wp-block-atomic-wind-text text-sm text-neutral-400 m-0" data-rich-text="">Founder &amp; CEO</span><!-- /wp:atomic-wind/text --></div><!-- /wp:atomic-wind/box --></div><!-- /wp:atomic-wind/box --></div><!-- /wp:atomic-wind/box --></section><!-- /wp:atomic-wind/box -->',
);
