<?php
/**
 * Call to Action with a Light Box
 *
 * @package ThemeIsle
 */

return array(
	'title'      => __( 'Call to Action with a Light Box', 'otter-blocks' ),
	'categories' => array( 'otter-blocks', 'cta' ),
	'content'    => '<!-- wp:themeisle-blocks/advanced-columns {"id":"wp-block-themeisle-blocks-advanced-columns-fecfcc1c","columns":1,"layout":"equal","layoutMobile":"collapsedRows","padding":{"top":"64px","right":"24px","bottom":"64px","left":"24px"},"paddingTablet":{"top":"64px","right":"24px","bottom":"64px","left":"24px"},"paddingMobile":{"top":"40px","bottom":"40px"},"margin":{"top":"0px","bottom":"0px"},"columnsWidth":960,"horizontalAlign":"center","columnsHeightCustom":600,"verticalAlign":"bottom","backgroundType":"image","backgroundImage":{"id":261,"url":"https://demosites.io/otter/wp-content/uploads/sites/664/2022/09/image-from-rawpixel-id-1054551-jpeg.jpg"},"backgroundPosition":{"x":0.5,"y":0.2},"backgroundRepeat":"no-repeat","backgroundSize":"cover","backgroundOverlayOpacity":10,"backgroundOverlayColor":"#000000","reverseColumnsMobile":true,"align":"full","className":"ticss-c00aadba","hasCustomCSS":true,"customCSS":""} --><div id="wp-block-themeisle-blocks-advanced-columns-fecfcc1c" class="wp-block-themeisle-blocks-advanced-columns alignfull has-1-columns has-desktop-equal-layout has-tablet-equal-layout has-mobile-collapsedRows-layout has-reverse-columns-mobile has-vertical-bottom ticss-c00aadba"><div class="wp-block-themeisle-blocks-advanced-columns-overlay"></div><div class="innerblocks-wrap"><!-- wp:themeisle-blocks/advanced-column {"id":"wp-block-themeisle-blocks-advanced-column-f5de8487","padding":{"top":"40px","right":"40px","bottom":"40px","left":"40px"},"paddingMobile":{"top":"24px","right":"24px","bottom":"24px","left":"24px"},"backgroundColor":"#ffffff","columnWidth":"100"} --><div id="wp-block-themeisle-blocks-advanced-column-f5de8487" class="wp-block-themeisle-blocks-advanced-column"><!-- wp:themeisle-blocks/advanced-heading {"id":"wp-block-themeisle-blocks-advanced-heading-c795af40","align":"center","alignTablet":"center","alignMobile":"center","fontSize":56,"fontSizeTablet":40,"fontSizeMobile":32} --><h2 id="wp-block-themeisle-blocks-advanced-heading-c795af40" class="wp-block-themeisle-blocks-advanced-heading wp-block-themeisle-blocks-advanced-heading-c795af40">A call to action section</h2><!-- /wp:themeisle-blocks/advanced-heading --><!-- wp:paragraph {"align":"center"} --><p class="has-text-align-center">Fusce consectetur, augue lobortis, erat eu sagittis egestas.</p><!-- /wp:paragraph --><!-- wp:buttons {"layout":{"type":"flex","justifyContent":"center"}} --><div class="wp-block-buttons"><!-- wp:button {"className":"is-style-primary","otterConditions":[]} --><div class="wp-block-button is-style-primary"><a class="wp-block-button__link">Learn More</a></div><!-- /wp:button --></div><!-- /wp:buttons --></div><!-- /wp:themeisle-blocks/advanced-column --></div></div><!-- /wp:themeisle-blocks/advanced-columns -->',
);
