<?php
/**
 * Two Columns Posts Section and a Description
 *
 * @package ThemeIsle
 */

return array(
	'title'      => __( 'Two Columns Posts Section and a Description', 'otter-blocks' ),
	'categories' => array( 'otter-blocks' ),
	'content'    => '<!-- wp:themeisle-blocks/advanced-columns {"id":"wp-block-themeisle-blocks-advanced-columns-5c0dfb97","columns":2,"layout":"equal","layoutTablet":"oneTwo","layoutMobile":"collapsedRows","padding":{"top":"64px","right":"24px","bottom":"64px","left":"24px"},"paddingTablet":{"top":"64px","right":"24px","bottom":"64px","left":"24px"},"paddingMobile":{"top":"40px","bottom":"40px"},"margin":{"top":"0px","bottom":"0px"},"columnsWidth":1140,"horizontalAlign":"center","verticalAlign":"top","align":"full","className":"ticss-c00aadba","hasCustomCSS":true,"customCSS":""} --><div id="wp-block-themeisle-blocks-advanced-columns-5c0dfb97" class="wp-block-themeisle-blocks-advanced-columns alignfull has-2-columns has-desktop-equal-layout has-tablet-oneTwo-layout has-mobile-collapsedRows-layout has-vertical-top ticss-c00aadba"><div class="wp-block-themeisle-blocks-advanced-columns-overlay"></div><div class="innerblocks-wrap"><!-- wp:themeisle-blocks/advanced-column {"id":"wp-block-themeisle-blocks-advanced-column-30cf692a","padding":{"top":"24px","right":"24px","bottom":"24px","left":"24px"},"columnWidth":"33.00"} --><div id="wp-block-themeisle-blocks-advanced-column-30cf692a" class="wp-block-themeisle-blocks-advanced-column"><!-- wp:themeisle-blocks/advanced-heading {"id":"wp-block-themeisle-blocks-advanced-heading-f33e78d3"} --><h2 id="wp-block-themeisle-blocks-advanced-heading-f33e78d3" class="wp-block-themeisle-blocks-advanced-heading wp-block-themeisle-blocks-advanced-heading-f33e78d3">Lastest Posts</h2><!-- /wp:themeisle-blocks/advanced-heading --><!-- wp:paragraph --><p>Sed ut perspiciatis unde omnis natus error sit vom accusantium.</p><!-- /wp:paragraph --></div><!-- /wp:themeisle-blocks/advanced-column --><!-- wp:themeisle-blocks/advanced-column {"id":"wp-block-themeisle-blocks-advanced-column-81e97556","padding":{"top":"24px","right":"24px","bottom":"24px","left":"24px"},"paddingMobile":{},"margin":{"left":"12px"},"marginMobile":{"top":"0px","right":"0px","bottom":"0px","left":"0px"},"columnWidth":"67.00"} --><div id="wp-block-themeisle-blocks-advanced-column-81e97556" class="wp-block-themeisle-blocks-advanced-column"><!-- wp:themeisle-blocks/posts-grid {"id":"wp-block-themeisle-blocks-posts-grid-dc1d7b52","columns":2,"template":["category","meta","title","description"],"displayCategory":false,"displayDescription":false,"displayComments":false} /--></div><!-- /wp:themeisle-blocks/advanced-column --></div></div><!-- /wp:themeisle-blocks/advanced-columns -->',
);
