name: InstaWP WordPress Testing

on:
  pull_request:
    types: [ opened, synchronize, ready_for_review ]

jobs:
  create-wp-for-testing:
    runs-on: ubuntu-latest
    steps:
      - uses: HardeepAsrani/otter-performance-testing@primary
        with:
          GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}
          INSTAWP_TOKEN: ${{ secrets.INSTAWP_TOKEN }}
          INSTAWP_TEMPLATE_SLUG: otter-qa
          ARTIFACT_URL: https://downloads.wordpress.org/plugin/otter-blocks.zip